---
- name: Install Jellyfin
  become: true
  tags: install
  block:

    - name: Create Jellyfin config directory
      ansible.builtin.file:
        path: /home/jellyfin/config
        state: directory
        mode: 0775
        owner: jellyfin
        group: jellyfin

    - name: Create Jellyfin cache directory
      ansible.builtin.file:
        path: /home/jellyfin/cache
        state: directory
        mode: 0775
        owner: jellyfin
        group: jellyfin

    - name: Create jellyfin_media volume
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr=nas.home,nolock,soft,rw"
          device: :/volume2/media/data/media
        volume_name: jellyfin_media

    - name: Instantiate passwd database
      getent:
        database: passwd

    - name: Create Jellyfin container
      community.docker.docker_container:
        name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        pull: true
        user: "{{ getent_passwd['jellyfin'].1 }}:{{ getent_passwd['jellyfin'].2 }}"
        restart_policy: unless-stopped
        volumes:
          - /home/jellyfin/config:/config
          - jellyfin_media:/data
        ports:
          - "80:{{ http_port }}"
          - "443:{{ https_port }}"
          - "{{ service_discovery_port }}:{{ service_discovery_port }}/udp"
          - "{{ auto_discovery_port }}:{{ auto_discovery_port }}/udp"
        env:
          TZ: Asia/Bangkok
          PUID: "{{ getent_passwd['bazarr'].1 }}"
          PGID: "{{ getent_passwd['bazarr'].2 }}"
          JELLYFIN_PublishedServerUrl: "{{ inventory_hostname }}"
