---
- name: Install Jellyfin
  become: true
  tags: install
  block:

    - name: Add 'jellyfin' user
      ansible.builtin.user:
        name: jellyfin
        group: media
        uid: "{{ uid }}"

    - name: Create Jellyfin config directory
      ansible.builtin.file:
        path: /home/jellyfin/config
        state: directory
        mode: 0775
        owner: jellyfin
        group: media

    - name: Create Jellyfin cache directory
      ansible.builtin.file:
        path: /home/jellyfin/cache
        state: directory
        mode: 0775
        owner: jellyfin
        group: media

    - name: Create jellyfin_media volume
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr=nas.home,rw,nfsvers=4,async"
          device: :/volume1/media/data
        volume_name: jellyfin_media

    - name: Instantiate passwd database
      getent:
        database: passwd

    - name: Create Jellyfin container
      community.docker.docker_container:
        name: jellyfin
        image: jellyfin/jellyfin:latest
        pull: true
        user: "{{ getent_passwd['jellyfin'].1 }}:{{ getent_passwd['jellyfin'].2 }}"
        restart_policy: unless-stopped
        volumes:
          - /home/jellyfin/config:/config
          - /home/jellyfin/cache:/cache
          - jellyfin_media:/media
        ports:
          - "{{ http_port }}:{{ http_port }}"
          - "{{ https_port }}:{{ https_port }}"
          - "{{ service_discovery_port }}:{{ service_discovery_port }}"
          - "{{ auto_discovery_port }}:{{ auto_discovery_port }}"
        env:
          JELLYFIN_PublishedServerUrl: "{{ inventory_hostname }}"
